name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"   # runs daily
  workflow_dispatch:     # allows manual run

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub Snake
        uses: Platane/snk@v3
        with:
          github_user_name: Mansi-2619

          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg

          # ðŸŽ¨ COLORS
          color_snake: "#2ecc71"     # green snake
          color_dots:
            - "#eeeeee"              # empty background (lightest grey)
            - "#eeeeee"
            - "#eeeeee"
            - "#eeeeee"
            - "#e74c3c"              # food box (red)

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Snake to Output Branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
